

lightprecision = 32

[skybox]

author = "bosurgi"
name = "moon1"
version = "v1"

[sky]

spin = 1
skytexture = 0
skytexturelight = 0

[sky.light]
r = 0
g = 0
b = 0

[sky.sunlight]
r = 0
g = 0
b = 0

[cloud]
alpha 0.7
scale 0.8

[cloud.layer]
author = "inexor"
name = "clouds02"
version = "v1"

[cloud.color]
r = 50
g = 70
b = 100

[cloud.scroll]
x = 0.01
y = 0.005

[fog]
distance = 1700
domemax = 0.8

[fog.colour]
r = 100
g = 110
b = 125

# [lava.colour]
# lavacolour 0x96C8FF

[lava.fog]
distance = 20

# [water.colour]
# watercolour 0x646464

[ambient]
r = 20
g = 20
b = 20

[ambientocclusion]
intensity = 110
radius = 5


#mapmodelreset
#
#// Bases
#
#base_1 = "The Bridge ^f2(Rockets)^f~"
#base_2 = "The Power Cells ^f5(Rifle)^f~"
#base_3 = "Test Room 1 ^f0(Chaingun)^f~"
#base_4 = "The Cell Reserve ^f9(Grenades)^f~"
#base_5 = "Break Room Entrance ^f3(Shotgun)^f~"
#base_6 = "The Observation Stage ^f5(Rifle)^f~"
#
#
#// Textures
#
#texturereset
#
#texture 0 "/inexor/sky.png"
#texture 0 "/inexor/default.png"
#
#// Yves Allaire (eX)
#
#setshader bumpspecmapparallaxworld
#setshaderparam specscale 3 3 3
#setshaderparam parallaxscale .04 -.02
#
#texture 0 "/evillair/ex/ex512/clangfloor_01b_d.jpg" 0 0 0 .5
#texture n "/evillair/ex/ex512/clangfloor_01_local.jpg"
#texture s "/evillair/ex/ex512/clangfloor_01_s.jpg"
#texture z "/evillair/ex/ex512/clangfloor_01_h.jpg"
#
#setshaderparam specscale .9 .9 .9
#
#texture 0 "/evillair/ex/ex512/cretefloor_01b_d.jpg" 0 0 0 .5
#texture n "/evillair/ex/ex512/cretefloor_01b_local.jpg"
#texture s "/evillair/ex/ex512/cretefloor_01b_s.jpg"
#texture z "/evillair/ex/ex512/cretefloor_01b_h.jpg"
#texscale .5
#
#setshaderparam specscale 3 3 3
#
#texture 0 "/evillair/ex/ex512/deswall_01_d.jpg" 0 0 0 .5
#texture n "/evillair/ex/ex512/deswall_01_local.jpg"
#texture s "/evillair/ex/ex512/deswall_01_s.jpg"
#texture z "/evillair/ex/ex512/deswall_01_h.jpg"
#texscale .5
#
#setshaderparam parallaxscale .02 -.01
#
#texture 0 "/evillair/ex/ex512/floor_grate03_d.jpg" 0 0 0 .5
#texture n "/evillair/ex/ex512/floor_grate03_local.jpg"
#texture s "/evillair/ex/ex512/floor_grate03_s.jpg"
#texture z "/evillair/ex/ex512/floor_grate03_h.jpg"
#texscale .5
#
#setshaderparam parallaxscale .04 -.02
#
#texture 0 "/evillair/ex/ex512/floor_mtl_grate_01_d.jpg" 0 0 0 .5
#texture n "/evillair/ex/ex512/floor_mtl_grate_01_local.jpg"
#texture s "/evillair/ex/ex512/floor_mtl_grate_01_s.jpg"
#texture z "/evillair/ex/ex512/floor_mtl_grate_01_h.jpg"
#texscale .5
#
#texture 0 "/evillair/ex/ex512/floor_simple_05_d.jpg" 0 0 0 .5
#texture n "/evillair/ex/ex512/floor_simple_05_local.jpg"
#texture s "/evillair/ex/ex512/floor_simple_05_s.jpg"
#texture z "/evillair/ex/ex512/floor_simple_05_h.jpg"
#
#texture 0 "/evillair/ex/ex512/floor_simplines_d.jpg" 0 0 0 .5
#texture n "/evillair/ex/ex512/floor_simplines_local.jpg" 
#texture s "/evillair/ex/ex512/floor_simplines_h.jpg" 
#texture z "/evillair/ex/ex512/floor_simplines_s.jpg" 
#
#texture 0 "/inexor/default.jpg"
#
#texture 0 "/evillair/ex/ex512/metalwall02_d.jpg" 0 0 0 .5
#texture n "/evillair/ex/ex512/metalwall02_local.jpg"
#texture s "/evillair/ex/ex512/metalwall02_s.jpg"
#texture z "/evillair/ex/ex512/metalwall02_h.jpg"
#
#texture 0 "/evillair/ex/ex512/mtl_bigplate_04_d.jpg" 0 0 0 .5
#texture n "/evillair/ex/ex512/mtl_bigplate_04_local.jpg"
#texture s "/evillair/ex/ex512/mtl_bigplate_04_s.jpg"
#texture z "/evillair/ex/ex512/mtl_bigplate_04_h.jpg"
#
#texture 0 "/evillair/ex/ex512/mtl_panel_02_d.jpg" 0 0 0 .5
#texture n "/evillair/ex/ex512/mtl_panel_02_local.jpg"
#texture s "/evillair/ex/ex512/mtl_panel_02_s.jpg"
#texture z "/evillair/ex/ex512/mtl_panel_02_h.jpg"
#
#texture 0 "/evillair/ex/ex512/mtl_panel_03_d.jpg" 0 0 0 .5
#texture n "/evillair/ex/ex512/mtl_panel_03_local.jpg"
#texture s "/evillair/ex/ex512/mtl_panel_03_s.jpg"
#texture z "/evillair/ex/ex512/mtl_panel_03_h.jpg"
#
#texture 0 "/evillair/ex/ex512/q2_01_d.jpg" 0 0 0 .5
#texture n "/evillair/ex/ex512/q2_01_local.jpg"
#texture s "/evillair/ex/ex512/q2_01_s.jpg"
#texture z "/evillair/ex/ex512/q2_01_h.jpg"
#texscale .5
#
#texture 0 "/evillair/ex/ex512/q2_01b_d.jpg" 0 0 0 .5
#texture n "/evillair/ex/ex512/q2_01b_local.jpg"
#texture s "/evillair/ex/ex512/q2_01b_s.jpg"
#texture z "/evillair/ex/ex512/q2_01b_h.jpg"
#texscale .5
#
#setshaderparam parallaxscale .02 -.01
#
#texture 0 "/evillair/ex/ex512/rndfloor_01_d.jpg" 0 0 0 .5
#texture n "/evillair/ex/ex512/rndfloor_01_local.jpg"
#texture s "/evillair/ex/ex512/rndfloor_01_s.jpg"
#texture z "/evillair/ex/ex512/rndfloor_01_h.jpg"
#
#texture 0 "/evillair/ex/ex512/rndfloor_02_d.jpg" 0 0 0 .5
#texture n "/evillair/ex/ex512/rndfloor_02_local.jpg"
#texture s "/evillair/ex/ex512/rndfloor_02_s.jpg"
#texture z "/evillair/ex/ex512/rndfloor_02_h.jpg"
#
#setshaderparam parallaxscale .04 -.02
#
#texture 0 "/evillair/ex/ex512/rplates_01_d.jpg" 0 0 0 .5
#texture n "/evillair/ex/ex512/rplates_01_local.jpg"
#texture s "/evillair/ex/ex512/rplates_01_s.jpg"
#texture z "/evillair/ex/ex512/rplates_01_h.jpg"
#
#texture 0 "/evillair/ex/ex512/trim_01_d.jpg" 0 0 0 .5
#texture n "/evillair/ex/ex512/trim_01_local.jpg"
#texture s "/evillair/ex/ex512/trim_01_s.jpg"
#texture z "/evillair/ex/ex512/trim_01_h.jpg"
#
#texture 0 "/evillair/ex/ex512/trim_baseboard_d.jpg" 0 0 0 .5
#texture n "/evillair/ex/ex512/trim_baseboard_local.jpg"
#texture s "/evillair/ex/ex512/trim_baseboard_s.jpg"
#texture z "/evillair/ex/ex512/trim_baseboard_h.jpg"
#
#texture 0 "/evillair/ex/ex512/trim_baseboard_02_d.jpg" 0 0 0 .5
#texture n "/evillair/ex/ex512/trim_baseboard_02_local.jpg"
#texture s "/evillair/ex/ex512/trim_baseboard_02_s.jpg"
#texture z "/evillair/ex/ex512/trim_baseboard_02_h.jpg"
#
#texture 0 "/evillair/ex/ex512/trim_psimple_04_d.jpg" 0 0 0 .5
#texture n "/evillair/ex/ex512/trim_psimple_04_local.jpg"
#texture s "/evillair/ex/ex512/trim_psimple_04_s.jpg"
#texture z "/evillair/ex/ex512/trim_psimple_04_h.jpg"
#
#texture 0 "/evillair/ex/ex512/trim_psimple_05_d.jpg" 0 0 0 .5
#texture n "/evillair/ex/ex512/trim_psimple_05_local.jpg"
#texture s "/evillair/ex/ex512/trim_psimple_05_s.jpg"
#texture z "/evillair/ex/ex512/trim_psimple_05_h.jpg"
#
#texture 0 "/evillair/ex/ex512/trim_simple_01_d.jpg" 0 0 0 .5
#texture n "/evillair/ex/ex512/trim_simple_01_local.jpg"
#texture s "/evillair/ex/ex512/trim_simple_01_s.jpg"
#texture z "/evillair/ex/ex512/trim_simple_01_h.jpg"
#
#texture 0 "/evillair/ex/ex512/wall_01_d.jpg" 0 0 0 .5
#texture n "/evillair/ex/ex512/wall_01_local.jpg"
#texture s "/evillair/ex/ex512/wall_01_s.jpg"
#texture z "/evillair/ex/ex512/wall_01_h.jpg"
#
#texture 0 "/evillair/ex/ex512/wall_b01_d.jpg" 0 0 0 .5
#texture n "/evillair/ex/ex512/wall_b01_local.jpg" 
#texture s "/evillair/ex/ex512/wall_b01_s.jpg"
#texture z "/evillair/ex/ex512/wall_b01_h.jpg"
#
#texture 0 "/evillair/ex/ex512/wall_bplate_06_d.jpg" 0 0 0 .5
#texture n "/evillair/ex/ex512/wall_bplate_06_local.jpg"
#texture s "/evillair/ex/ex512/wall_bplate_06_s.jpg"
#texture z "/evillair/ex/ex512/wall_bplate_06_h.jpg"
#
#setshaderparam parallaxscale .025 -.01
#
#texture 0 "/evillair/ex/ex512/wall_pipe_d.jpg" 0 0 0 .5
#texture n "/evillair/ex/ex512/wall_pipe_local.jpg"
#texture s "/evillair/ex/ex512/wall_pipe_s.jpg"
#texture z "/evillair/ex/ex512/wall_pipe_h.jpg"
#
#setshaderparam parallaxscale .04 -.02
#
#texture 0 "/evillair/ex/ex512/wall_u207_d.jpg" 0 0 0 .5
#texture n "/evillair/ex/ex512/wall_u207_local.jpg"
#texture s "/evillair/ex/ex512/wall_u207_s.jpg"
#texture z "/evillair/ex/ex512/wall_u207_h.jpg"
#
#texture 0 "/evillair/ex/ex512/metal_plate01b_d.jpg" 0 0 0 .5
#texture n "/evillair/ex/ex512/metal_plate01b_local.jpg"
#texture s "/evillair/ex/ex512/metal_plate01b_s.jpg"
#texture z "/evillair/ex/ex512/metal_plate01b_h.jpg"
#
#texture 0 "/evillair/ex/ex512/metal_plate01c_d.jpg" 0 0 0 .5
#texture n "/evillair/ex/ex512/metal_plate01c_local.jpg"
#texture s "/evillair/ex/ex512/metal_plate01c_s.jpg"
#texture z "/evillair/ex/ex512/metal_plate01c_h.jpg"
#
#texture 0 "/evillair/ex/ex512/metalbase01_d.jpg" 0 0 0 .5
#texture n "/evillair/ex/ex512/metalbase01_local.jpg"
#texture s "/evillair/ex/ex512/metalbase01_s.jpg"
#texture z "/evillair/ex/ex512/metalbase01_h.jpg"
#
#
#texture 0 "/evillair/ex/ex512/metalbase04_d.jpg" 0 0 0 .5
#texture n "/evillair/ex/ex512/metalbase03_local.jpg"
#texture s "/evillair/ex/ex512/metalbase03_s.jpg"
#texture z "/evillair/ex/ex512/metalbase03_h.jpg"
#
#texture 0 "/inexor/default.jpg"
#
#texture 0 "/evillair/ex/ex512/metalfloor02_d.jpg" 0 0 0 .5
#texture n "/evillair/ex/ex512/metalfloor02_local.jpg"
#texture s "/evillair/ex/ex512/metalfloor02_s.jpg"
#texture z "/evillair/ex/ex512/metalfloor02_h.jpg"
#
#setshader bumpspecmapparallaxglowworld
#setshaderparam specscale 1.5 1.5 1.5
#setshaderparam parallaxscale .04 -.02
#setshaderparam glowcolor .5 .8 1
#
#texture 0 "/evillair/ex/ex512/light_u201_d.jpg" 0 0 0 .5
#texture n "/evillair/ex/ex512/light_u201_local.jpg"
#texture s "/evillair/ex/ex512/light_u201_s.jpg"
#texture g "/evillair/ex/ex512/light_u201_add.jpg"
#texture z "/evillair/ex/ex512/light_u201_h.jpg"
#
#texture 0 "/evillair/ex/ex512/lightpanel_01_d.jpg" 0 0 0 .5
#texture n "/evillair/ex/ex512/lightpanel_01_local.jpg"
#texture s "/evillair/ex/ex512/lightpanel_01_s.jpg"
#texture g "/evillair/ex/ex512/lightpanel_01_add.jpg"
#texture z "/evillair/ex/ex512/lightpanel_01_h.jpg"
#
#setshader bumpspecmapparallaxglowworld
#setshaderparam specscale 1.5 1.5 1.5
#setshaderparam parallaxscale .04 -.02
#setshaderparam glowcolor .5 .4 1
#
#texture 0 "/evillair/ex/ex512/lightpanel_01_d.jpg" 0 0 0 .5
#texture n "/evillair/ex/ex512/lightpanel_01_local.jpg"
#texture s "/evillair/ex/ex512/lightpanel_01_s.jpg"
#texture g "/evillair/ex/ex512/lightpanel_01_add.jpg"
#texture z "/evillair/ex/ex512/lightpanel_01_h.jpg"
#
#texture 0 "/evillair/ex/ex512/light_u201_d.jpg" 0 0 0 .5
#texture n "/evillair/ex/ex512/light_u201_local.jpg"
#texture s "/evillair/ex/ex512/light_u201_s.jpg"
#texture g "/evillair/ex/ex512/light_u201_add.jpg"
#texture z "/evillair/ex/ex512/light_u201_h.jpg"
#
#
#texture 0 "/inexor/default.jpg"
#
#
#// philipk (pk01)
#
#setshader bumpspecmapglowworld
#setshaderparam "specscale" 4 4 4
#texture 0 "/philipk/pk01/pk01_panel_small01_d.jpg"
#texture n "/philipk/pk01/pk01_panel_small01_local.jpg"
#texture s "/philipk/pk01/pk01_panel_small01_s.jpg"
#texture g "/philipk/pk01/pk01_panel_small01_add.jpg"
#
#texture 0 "/inexor/default.jpg"
#
#
#// sheik
#
#setshader glowworld
#setshaderparam glowcolor .7 1 1
#texture 0 "/sheik/cell2.png" 0 0 0 .25
#texscroll -.05 .01 
#texcolor .7 1 1
#
#setshaderparam glowcolor .8 .7 1
#texture 0 "/sheik/cell2.png" 0 0 0 .25
#texcolor .8 .7 1
#texscroll .05 .01 
#
#
#// Lava Texture
#
#materialreset
#
#loop i 4 [
#    texture [water@(+ $i 1)] "/inexor/material/water/water.png"    // water surface
#    texture 1 "/inexor/material/water/waterfall.png"     // waterfall
#    texture 1 "/inexor/material/water/water_calm_normal.png"        // water normals
#    texture 1 "/inexor/material/water/foam.png" //"../texture/waterdudv.jpg"     // TODO: water distortion
#    texture 1 "/inexor/material/water/waterfall_normal.png"    // waterfall normals
#    texture 1 "/inexor/material/water/foam.png" // TODO: waterfall distortion
#
#    texture [lava@(+ $i 1)] "/sheik/plasma.png" 0 0 0 2 // lava surface
#    texture 1 "/sheik/plasma.png"    0 0 0 2 // "dg/floor_lava2.jpg" // TODO: falling lava
#]
#
#
#
#// texture water "golgotha/water2.jpg"
#// texture 1 "/waterfall.jpg"
#// texture 1 "/watern.jpg"
#// texture 1 "/waterdudv.jpg"
#// texture 1 "/waterfalln.jpg"
#// texture 1 "/waterfalldudv.jpg"
#// texture lava "/sheik/"/plasma.png" 0 0 0 3
#// texture 1 "/sheik/"/plasma.png"	

